/*
 * Writes assets/icons.css: the @font-face and base rules from the full Nerdfonts
 * stylesheet, plus a rule for each glyph this pack names, and nothing else.
 *
 *   node scripts/build-icons.mjs
 *
 * Why: assets/nerdfonts.css is 495KB of about ten thousand selectors. Every panel
 * is a fresh page, so all of it was parsed again on every open, before anything
 * could be drawn. The pack uses a few dozen glyphs.
 *
 * Glyph names are collected by scanning the pack for `nf-...` tokens, which finds
 * both the ones written into class attributes and the ones assembled in script
 * ('nf ' + volumeIcon(...)). A glyph name built up from pieces at runtime would
 * not be found, so keep them whole in the source.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const packDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(packDir, 'assets', 'nerdfonts.css');
const target = join(packDir, 'assets', 'icons.css');

const SCAN_EXTENSIONS = new Set(['.html', '.js', '.mjs', '.css']);
const SKIP_DIRS = new Set(['.git', 'node_modules', 'resources', 'vendor']);
// Unused starter leftovers: their glyphs would pad the file for no reason.
const SKIP_FILES = new Set([
  'with-glazewm.html',
  'with-komorebi.html',
  'nerdfonts.css',
  'icons.css',
]);

function collectFiles(dir) {
  const found = [];

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      found.push(...collectFiles(join(dir, entry.name)));
      continue;
    }

    if (SKIP_FILES.has(entry.name)) continue;
    if (!SCAN_EXTENSIONS.has(extname(entry.name))) continue;

    found.push(join(dir, entry.name));
  }

  return found;
}

const used = new Set();

for (const file of collectFiles(packDir)) {
  const text = readFileSync(file, 'utf8');

  for (const match of text.matchAll(/\bnf-[a-z0-9]+-[a-z0-9_]+\b/g)) {
    used.add(match[0]);
  }
}

const css = readFileSync(source, 'utf8');

// The @font-face block and the shared `.nf` rule, both at the top of the file.
const preamble = css.match(/@font-face\{[^}]*\}[^@]*?\.nf,[^{]*\{[^}]*\}/);

if (!preamble) {
  console.error('Could not find the @font-face and .nf rules in ' + source);
  process.exit(1);
}

const rules = [];
const missing = [];

for (const name of [...used].sort()) {
  const rule = css.match(
    new RegExp('\\.' + name + ':before\\{content:"[^"]*"\\}'),
  );

  if (!rule) {
    missing.push(name);
    continue;
  }

  rules.push(rule[0]);
}

const out =
  '/*\n' +
  ' * GENERATED by scripts/build-icons.mjs. Do not edit.\n' +
  ' *\n' +
  ' * Only the glyphs this pack uses, taken from assets/nerdfonts.css. Add a new\n' +
  ' * icon to a widget, then run: node scripts/build-icons.mjs\n' +
  ' */\n' +
  preamble[0] +
  '\n' +
  rules.join('\n') +
  '\n';

writeFileSync(target, out);

console.log(
  `icons.css: ${rules.length} glyphs, ${(out.length / 1024).toFixed(1)}KB ` +
    `(from ${(css.length / 1024).toFixed(0)}KB)`,
);

if (missing.length) {
  console.log('not found in the font stylesheet: ' + missing.join(', '));
}
